local love = {
  read_only = true,
  fields = {
    getVersion = {},
    conf = { read_only = false },
    directorydropped = { read_only = false },
    draw = { read_only = false },
    errhand = { read_only = false },
    filedropped = { read_only = false },
    focus = { read_only = false },
    gamepadaxis = { read_only = false },
    gamepadpressed = { read_only = false },
    gamepadreleased = { read_only = false },
    joystickadded = { read_only = false },
    joystickaxis = { read_only = false },
    joystickhat = { read_only = false },
    joystickpressed = { read_only = false },
    joystickreleased = { read_only = false },
    joystickremoved = { read_only = false },
    keypressed = { read_only = false },
    keyreleased = { read_only = false },
    load = { read_only = false },
    lowmemory = { read_only = false },
    mousefocus = { read_only = false },
    mousemoved = { read_only = false },
    mousepressed = { read_only = false },
    mousereleased = { read_only = false },
    quit = { read_only = false },
    resize = { read_only = false },
    run = { read_only = false },
    textedited = { read_only = false },
    textinput = { read_only = false },
    threaderror = { read_only = false },
    touchmoved = { read_only = false },
    touchpressed = { read_only = false },
    touchreleased = { read_only = false },
    update = { read_only = false },
    visible = { read_only = false },
    wheelmoved = { read_only = false },
    audio = {
      fields = {
        getDistanceModel = {},
        getDopplerScale = {},
        getSourceCount = {},
        getOrientation = {},
        getPosition = {},
        getVelocity = {},
        getVolume = {},
        newSource = {},
        pause = {},
        play = {},
        resume = {},
        rewind = {},
        setDistanceModel = {},
        setDopplerScale = {},
        setOrientation = {},
        setPosition = {},
        setVelocity = {},
        setVolume = {},
        stop = {},
      },
    },
    event = {
      fields = {
        clear = {},
        poll = {},
        pump = {},
        push = {},
        quit = {},
        wait = {},
      },
    },
    filesystem = {
      fields = {
        append = {},
        areSymlinksEnabled = {},
        createDirectory = {},
        exists = {},
        getAppdataDirectory = {},
        getDirectoryItems = {},
        getIdentity = {},
        getLastModified = {},
        getRealDirectory = {},
        getRequirePath = {},
        getSaveDirectory = {},
        getSize = {},
        getSource = {},
        getSourceBaseDirectory = {},
        getUserDirectory = {},
        getWorkingDirectory = {},
        init = {},
        isDirectory = {},
        isFile = {},
        isFused = {},
        isSymlink = {},
        lines = {},
        load = {},
        mount = {},
        newFile = {},
        newFileData = {},
        read = {},
        remove = {},
        setIdentity = {},
        setRequirePath = {},
        setSource = {},
        setSymlinksEnabled = {},
        unmount = {},
        write = {},
      },
    },
    graphics = {
      fields = {
        arc = {},
        circle = {},
        clear = {},
        discard = {},
        draw = {},
        ellipse = {},
        getBackgroundColor = {},
        getBlendMode = {},
        getCanvas = {},
        getCanvasFormats = {},
        getColor = {},
        getColorMask = {},
        getCompressedImageFormats = {},
        getDefaultFilter = {},
        getDimensions = {},
        getFont = {},
        getHeight = {},
        getLineJoin = {},
        getLineStyle = {},
        getLineWidth = {},
        getShader = {},
        getStats = {},
        getStencilTest = {},
        getSupported = {},
        getSystemLimits = {},
        getPointSize = {},
        getRendererInfo = {},
        getScissor = {},
        getWidth = {},
        intersectScissor = {},
        isGammaCorrect = {},
        isWireframe = {},
        line = {},
        newCanvas = {},
        newFont = {},
        newMesh = {},
        newImage = {},
        newImageFont = {},
        newParticleSystem = {},
        newShader = {},
        newText = {},
        newQuad = {},
        newScreenshot = {},
        newSpriteBatch = {},
        newVideo = {},
        origin = {},
        points = {},
        polygon = {},
        pop = {},
        present = {},
        print = {},
        printf = {},
        push = {},
        rectangle = {},
        reset = {},
        rotate = {},
        scale = {},
        setBackgroundColor = {},
        setBlendMode = {},
        setCanvas = {},
        setColor = {},
        setColorMask = {},
        setDefaultFilter = {},
        setFont = {},
        setLineJoin = {},
        setLineStyle = {},
        setLineWidth = {},
        setNewFont = {},
        setShader = {},
        setPointSize = {},
        setScissor = {},
        setStencilTest = {},
        setWireframe = {},
        shear = {},
        stencil = {},
        translate = {},
      },
    },
    image = {
      fields = {
        isCompressed = {},
        newCompressedData = {},
        newImageData = {},
      },
    },
    joystick = {
      fields = {
        getJoystickCount = {},
        getJoysticks = {},
        loadGamepadMappings = {},
        saveGamepadMappings = {},
        setGamepadMapping = {},
      },
    },
    keyboard = {
      fields = {
        getKeyFromScancode = {},
        getScancodeFromKey = {},
        hasKeyRepeat = {},
        hasTextInput = {},
        isDown = {},
        isScancodeDown = {},
        setKeyRepeat = {},
        setTextInput = {},
      },
    },
    math = {
      fields = {
        compress = {},
        decompress = {},
        gammaToLinear = {},
        getRandomSeed = {},
        getRandomState = {},
        isConvex = {},
        linearToGamma = {},
        newBezierCurve = {},
        newRandomGenerator = {},
        noise = {},
        random = {},
        randomNormal = {},
        setRandomSeed = {},
        setRandomState = {},
        triangulate = {},
      },
    },
    mouse = {
      fields = {
        getCursor = {},
        getPosition = {},
        getRelativeMode = {},
        getSystemCursor = {},
        getX = {},
        getY = {},
        hasCursor = {},
        isDown = {},
        isGrabbed = {},
        isVisible = {},
        newCursor = {},
        setCursor = {},
        setGrabbed = {},
        setPosition = {},
        setRelativeMode = {},
        setVisible = {},
        setX = {},
        setY = {},
      },
    },
    physics = {
      fields = {
        getDistance = {},
        getMeter = {},
        newBody = {},
        newChainShape = {},
        newCircleShape = {},
        newDistanceJoint = {},
        newEdgeShape = {},
        newFixture = {},
        newFrictionJoint = {},
        newGearJoint = {},
        newMotorJoint = {},
        newMouseJoint = {},
        newPolygonShape = {},
        newPrismaticJoint = {},
        newPulleyJoint = {},
        newRectangleShape = {},
        newRevoluteJoint = {},
        newRopeJoint = {},
        newWeldJoint = {},
        newWheelJoint = {},
        newWorld = {},
        setMeter = {},
      },
    },
    sound = {
      fields = {
        newDecoder = {},
        newSoundData = {},
      },
    },
    system = {
      fields = {
        getClipboardText = {},
        getOS = {},
        getPowerInfo = {},
        getProcessorCount = {},
        openURL = {},
        setClipboardText = {},
        vibrate = {},
      },
    },
    thread = {
      fields = {
        getChannel = {},
        newChannel = {},
        newThread = {},
      },
    },
    timer = {
      fields = {
        getAverageDelta = {},
        getDelta = {},
        getFPS = {},
        getTime = {},
        sleep = {},
        step = {},
      },
    },
    touch = {
      fields = {
        getPosition = {},
        getPressure = {},
        getTouches = {},
      },
    },
    video = {
      fields = {
        newVideoStream = {},
      },
    },
    window = {
      fields = {
        close = {},
        fromPixels = {},
        getDisplayName = {},
        getFullscreen = {},
        getFullscreenModes = {},
        getIcon = {},
        getMode = {},
        getPixelScale = {},
        getPosition = {},
        getTitle = {},
        hasFocus = {},
        hasMouseFocus = {},
        isDisplaySleepEnabled = {},
        isMaximized = {},
        isOpen = {},
        isVisible = {},
        maximize = {},
        minimize = {},
        requestAttention = {},
        setDisplaySleepEnabled = {},
        setFullscreen = {},
        setIcon = {},
        setMode = {},
        setPosition = {},
        setTitle = {},
        showMessageBox = {},
        toPixels = {},
      },
    },
  },
}

return love