local empty, read_write = {}, { read_only = false }

local love = {
  read_only = true,
  fields = {
    getVersion = empty,
    conf = read_write,
    directorydropped = read_write,
    draw = read_write,
    errhand = read_write,
    filedropped = read_write,
    focus = read_write,
    gamepadaxis = read_write,
    gamepadpressed = read_write,
    gamepadreleased = read_write,
    joystickadded = read_write,
    joystickaxis = read_write,
    joystickhat = read_write,
    joystickpressed = read_write,
    joystickreleased = read_write,
    joystickremoved = read_write,
    keypressed = read_write,
    keyreleased = read_write,
    load = read_write,
    lowmemory = read_write,
    mousefocus = read_write,
    mousemoved = read_write,
    mousepressed = read_write,
    mousereleased = read_write,
    quit = read_write,
    resize = read_write,
    run = read_write,
    textedited = read_write,
    textinput = read_write,
    threaderror = read_write,
    touchmoved = read_write,
    touchpressed = read_write,
    touchreleased = read_write,
    update = read_write,
    visible = read_write,
    wheelmoved = read_write,
    audio = {
      fields = {
        getDistanceModel = empty,
        getDopplerScale = empty,
        getSourceCount = empty,
        getOrientation = empty,
        getPosition = empty,
        getVelocity = empty,
        getVolume = empty,
        newSource = empty,
        pause = empty,
        play = empty,
        resume = empty,
        rewind = empty,
        setDistanceModel = empty,
        setDopplerScale = empty,
        setOrientation = empty,
        setPosition = empty,
        setVelocity = empty,
        setVolume = empty,
        stop = empty,
      },
    },
    event = {
      fields = {
        clear = empty,
        poll = empty,
        pump = empty,
        push = empty,
        quit = empty,
        wait = empty,
      },
    },
    filesystem = {
      fields = {
        append = empty,
        areSymlinksEnabled = empty,
        createDirectory = empty,
        exists = empty,
        getAppdataDirectory = empty,
        getDirectoryItems = empty,
        getIdentity = empty,
        getLastModified = empty,
        getRealDirectory = empty,
        getRequirePath = empty,
        getSaveDirectory = empty,
        getSize = empty,
        getSource = empty,
        getSourceBaseDirectory = empty,
        getUserDirectory = empty,
        getWorkingDirectory = empty,
        init = empty,
        isDirectory = empty,
        isFile = empty,
        isFused = empty,
        isSymlink = empty,
        lines = empty,
        load = empty,
        mount = empty,
        newFile = empty,
        newFileData = empty,
        read = empty,
        remove = empty,
        setIdentity = empty,
        setRequirePath = empty,
        setSource = empty,
        setSymlinksEnabled = empty,
        unmount = empty,
        write = empty,
      },
    },
    graphics = {
      fields = {
        arc = empty,
        circle = empty,
        clear = empty,
        discard = empty,
        draw = empty,
        ellipse = empty,
        getBackgroundColor = empty,
        getBlendMode = empty,
        getCanvas = empty,
        getCanvasFormats = empty,
        getColor = empty,
        getColorMask = empty,
        getCompressedImageFormats = empty,
        getDefaultFilter = empty,
        getDimensions = empty,
        getFont = empty,
        getHeight = empty,
        getLineJoin = empty,
        getLineStyle = empty,
        getLineWidth = empty,
        getShader = empty,
        getStats = empty,
        getStencilTest = empty,
        getSupported = empty,
        getSystemLimits = empty,
        getPointSize = empty,
        getRendererInfo = empty,
        getScissor = empty,
        getWidth = empty,
        intersectScissor = empty,
        isGammaCorrect = empty,
        isWireframe = empty,
        line = empty,
        newCanvas = empty,
        newFont = empty,
        newMesh = empty,
        newImage = empty,
        newImageFont = empty,
        newParticleSystem = empty,
        newShader = empty,
        newText = empty,
        newQuad = empty,
        newScreenshot = empty,
        newSpriteBatch = empty,
        newVideo = empty,
        origin = empty,
        points = empty,
        polygon = empty,
        pop = empty,
        present = empty,
        print = empty,
        printf = empty,
        push = empty,
        rectangle = empty,
        reset = empty,
        rotate = empty,
        scale = empty,
        setBackgroundColor = empty,
        setBlendMode = empty,
        setCanvas = empty,
        setColor = empty,
        setColorMask = empty,
        setDefaultFilter = empty,
        setFont = empty,
        setLineJoin = empty,
        setLineStyle = empty,
        setLineWidth = empty,
        setNewFont = empty,
        setShader = empty,
        setPointSize = empty,
        setScissor = empty,
        setStencilTest = empty,
        setWireframe = empty,
        shear = empty,
        stencil = empty,
        translate = empty,
      },
    },
    image = {
      fields = {
        isCompressed = empty,
        newCompressedData = empty,
        newImageData = empty,
      },
    },
    joystick = {
      fields = {
        getJoystickCount = empty,
        getJoysticks = empty,
        loadGamepadMappings = empty,
        saveGamepadMappings = empty,
        setGamepadMapping = empty,
      },
    },
    keyboard = {
      fields = {
        getKeyFromScancode = empty,
        getScancodeFromKey = empty,
        hasKeyRepeat = empty,
        hasTextInput = empty,
        isDown = empty,
        isScancodeDown = empty,
        setKeyRepeat = empty,
        setTextInput = empty,
      },
    },
    math = {
      fields = {
        compress = empty,
        decompress = empty,
        gammaToLinear = empty,
        getRandomSeed = empty,
        getRandomState = empty,
        isConvex = empty,
        linearToGamma = empty,
        newBezierCurve = empty,
        newRandomGenerator = empty,
        noise = empty,
        random = empty,
        randomNormal = empty,
        setRandomSeed = empty,
        setRandomState = empty,
        triangulate = empty,
      },
    },
    mouse = {
      fields = {
        getCursor = empty,
        getPosition = empty,
        getRelativeMode = empty,
        getSystemCursor = empty,
        getX = empty,
        getY = empty,
        hasCursor = empty,
        isDown = empty,
        isGrabbed = empty,
        isVisible = empty,
        newCursor = empty,
        setCursor = empty,
        setGrabbed = empty,
        setPosition = empty,
        setRelativeMode = empty,
        setVisible = empty,
        setX = empty,
        setY = empty,
      },
    },
    physics = {
      fields = {
        getDistance = empty,
        getMeter = empty,
        newBody = empty,
        newChainShape = empty,
        newCircleShape = empty,
        newDistanceJoint = empty,
        newEdgeShape = empty,
        newFixture = empty,
        newFrictionJoint = empty,
        newGearJoint = empty,
        newMotorJoint = empty,
        newMouseJoint = empty,
        newPolygonShape = empty,
        newPrismaticJoint = empty,
        newPulleyJoint = empty,
        newRectangleShape = empty,
        newRevoluteJoint = empty,
        newRopeJoint = empty,
        newWeldJoint = empty,
        newWheelJoint = empty,
        newWorld = empty,
        setMeter = empty,
      },
    },
    sound = {
      fields = {
        newDecoder = empty,
        newSoundData = empty,
      },
    },
    system = {
      fields = {
        getClipboardText = empty,
        getOS = empty,
        getPowerInfo = empty,
        getProcessorCount = empty,
        openURL = empty,
        setClipboardText = empty,
        vibrate = empty,
      },
    },
    thread = {
      fields = {
        getChannel = empty,
        newChannel = empty,
        newThread = empty,
      },
    },
    timer = {
      fields = {
        getAverageDelta = empty,
        getDelta = empty,
        getFPS = empty,
        getTime = empty,
        sleep = empty,
        step = empty,
      },
    },
    touch = {
      fields = {
        getPosition = empty,
        getPressure = empty,
        getTouches = empty,
      },
    },
    video = {
      fields = {
        newVideoStream = empty,
      },
    },
    window = {
      fields = {
        close = empty,
        fromPixels = empty,
        getDisplayName = empty,
        getFullscreen = empty,
        getFullscreenModes = empty,
        getIcon = empty,
        getMode = empty,
        getPixelScale = empty,
        getPosition = empty,
        getTitle = empty,
        hasFocus = empty,
        hasMouseFocus = empty,
        isDisplaySleepEnabled = empty,
        isMaximized = empty,
        isOpen = empty,
        isVisible = empty,
        maximize = empty,
        minimize = empty,
        requestAttention = empty,
        setDisplaySleepEnabled = empty,
        setFullscreen = empty,
        setIcon = empty,
        setMode = empty,
        setPosition = empty,
        setTitle = empty,
        showMessageBox = empty,
        toPixels = empty,
      },
    },
  },
}

return love